### ISSUE TITLE
Example not working with matplotlib 3.3.3

### ISSUE THREAD

**Issue by bastidest** [nschloe/tikzplotlib#446]
Tikzplotlib crashes when used with matplotlib 3.3.3. Using matplotlib 3.3.2 works as expected.

### Environment
- tikzplotlib 0.9.4
- matplotlib 3.3.3
- Arch Linux (5.9.6-arch1-1)

### Example
```python
import matplotlib.pyplot as plt
import numpy as np

plt.style.use("ggplot")

t = np.arange(0.0, 2.0, 0.1)
s = np.sin(2 * np.pi * t)
s2 = np.cos(2 * np.pi * t)
plt.plot(t, s, "o-", lw=4.1)
plt.plot(t, s2, "o-", lw=4.1)
plt.xlabel("time (s)")
plt.ylabel("Voltage (mV)")
plt.title("Simple plot $\\frac{\\alpha}{2}$")
plt.grid(True)

import tikzplotlib

tikzplotlib.save("test.tex")
```

### Trace
```
Traceback (most recent call last):
  File "test.py", line 18, in <module>
    tikzplotlib.save("test.tex")
  File "/usr/lib/python3.8/site-packages/tikzplotlib/_save.py", line 253, in save
    code = get_tikz_code(*args, filepath=filepath, **kwargs)
  File "/usr/lib/python3.8/site-packages/tikzplotlib/_save.py", line 207, in get_tikz_code
    data, content = _recurse(data, figure)
  File "/usr/lib/python3.8/site-packages/tikzplotlib/_save.py", line 335, in _recurse
    ax = _axes.Axes(data, child)
  File "/usr/lib/python3.8/site-packages/tikzplotlib/_axes.py", line 124, in __init__
    self._grid(obj, data)
  File "/usr/lib/python3.8/site-packages/tikzplotlib/_axes.py", line 298, in _grid
    if obj.xaxis._gridOnMajor:
AttributeError: 'XAxis' object has no attribute '_gridOnMajor'
```

**Comment by nschloe** [comment]
Thanks for the good report. A fix is now released.
